add language list setting for webuser

diff --git a/jobs/paas-ta-portal-webuser/templates/bin/pre_start.erb b/jobs/paas-ta-portal-webuser/templates/bin/pre_start.erb
--- a/jobs/paas-ta-portal-webuser/templates/bin/pre_start.erb
+++ b/jobs/paas-ta-portal-webuser/templates/bin/pre_start.erb
@@ -28,23 +28,47 @@ DEL_PATH="$PKG_DIR/$JOB_NAME/$JOB_NAME"
 echo $DEL_PATH
 if [ -d $DEL_PATH ]
 then
-  echo fount
+  echo "found"
   sudo rm -r $PKG_DIR/$JOB_NAME/$JOB_NAME
 else
   echo "not found"
 fi
 
 
-tar xvf $PKG_DIR/$JOB_NAME/$JOB_NAME.tar.gz -C $PKG_DIR/$JOB_NAME
+tar xf $PKG_DIR/$JOB_NAME/$JOB_NAME.tar.gz -C $PKG_DIR/$JOB_NAME
 
 
 MAIN_JS=$(find ${WEB_FILE} -type f -name main.*.js)
 PRE_APPCONFIG="${WEB_FILE}/assets/resources/env/config.json"
+LANG_DIR_PATH="${WEB_FILE}/assets/i18n"
+LOG_PATH="/var/vcap/sys/log/monit/$JOB_NAME.err.log"
 
 
-PRE_FILTER=$(cat ${PRE_APPCONFIG} | tr -d '{'  |tr -d '\r\n' | tr -d '"' | sed -e 's/: /:\"/g' | sed -e 's/,  /\",/g' | sed -e 's/^ *//g' -e 's/ *$//g' | sed -e 's/}/"/g' | sed -e 's/"false"/!1/g' | sed -e 's/"true"/!0/g'| sed -e 's/\//\\\//g' )
-AFTER_FILTER=$(cat ${JOB_APPCONFIG} | tr -d '{'  |tr -d '\r\n' | tr -d '"' | sed -e 's/: /:\"/g' | sed -e 's/,  /\",/g' | sed -e 's/^ *//g' -e 's/ *$//g' | sed -e 's/}/"/g' | sed -e 's/"false"/!1/g' | sed -e 's/"true"/!0/g'| sed -e 's/\//\\\//g')
+PRE_LANG=()
+for file in `ls $LANG_DIR_PATH/*`
+do
+        PRE_LANG+=(`basename -s ".json" "${file}"`)
+done
 
+AFTER_LANG=$(grep "\[" ${JOB_APPCONFIG} | tr -d '\[' | tr -d '\]' | tr -d '"' | tr -d ' ' | tr -d '\r' | cut -d ":" -f2)
+IFS=',' read -r -a AFTER_LANG_LIST <<< "$AFTER_LANG"
+
+if [[ ${#AFTER_LANG_LIST[@]} -eq 0 ]]; then
+        echo "Error: Language list does not exist" >> $LOG_PATH
+        exit 1
+else
+        for element in ${AFTER_LANG_LIST[@]}
+        do
+                if [[ ! ${PRE_LANG[@]} =~ ${element} ]]; then
+                        echo "Error: \"${element}\" is unsupported language" >> $LOG_PATH
+                        exit 1
+                fi
+        done
+fi
+
+
+PRE_FILTER=$(cat ${PRE_APPCONFIG} | tr -d '{'  |tr -d '\r\n' | tr -d '"' | sed -e 's/: /:\"/g' | sed -e 's/,  /\",/g' | sed -e 's/^ *//g' -e 's/ *$//g' | sed -e 's/}/"/g' | sed -e 's/"false"/!1/g' | sed -e 's/"true"/!0/g'| sed -e 's/\//\\\//g' | sed -e 's/, /\",\"/g' | sed -e 's/\"\[/\\[\"/g' | sed -e 's/\]\"/\"\\]/g')
+AFTER_FILTER=$(cat ${JOB_APPCONFIG} | tr -d '{'  |tr -d '\r\n' | tr -d '"' | sed -e 's/: /:\"/g' | sed -e 's/,/\",\"/g' | sed -e 's/\"  //g' | sed -e 's/^ *//g' -e 's/ *$//g' | sed -e 's/}/"/g' | sed -e 's/"false"/!1/g' | sed -e 's/"true"/!0/g'| sed -e 's/\//\\\//g' | sed -e 's/\"\[/\\[\"/g' | sed -e 's/\]\"/\"\\]/g' | sed -e 's/\" /\"/g')
 
 CONFIG_CHANGE="'s/${PRE_FILTER}/${AFTER_FILTER}/g' ${MAIN_JS}"
 
